FROM python:3.9-slim

WORKDIR /usr/src/app

COPY ./requirements.txt ./

RUN apt-get update && apt-get -y install git vim

RUN git config --global core.filemode false

RUN pip install -r ./requirements.txt --no-cache-dir
